'use strict';
const SUPABASE='https://zszsayplgifdvmjowupy.supabase.co';
const ANON='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzenNheXBsZ2lmZHZtam93dXB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTAxNjM2NTAsImV4cCI6MjEwNTczOTY1MH0.aP8DBAOnoPNPNecN-CVTy65sn6-G6xtV96CbYmApCWQ';
const state={session:null,user:null,profile:null,rooms:[],clans:[],memberships:[],messages:[],room:null,key:null,page:'home'};
const $=selector=>document.querySelector(selector);const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const b64=bytes=>{let s='';new Uint8Array(bytes).forEach(byte=>s+=String.fromCharCode(byte));return btoa(s)};const unb64=value=>Uint8Array.from(atob(value),c=>c.charCodeAt(0));
function b64url(value){return String(value).replaceAll('+','-').replaceAll('/','_').replace(/=+$/g,'')}
function xmlToJwk(xml){const doc=new DOMParser().parseFromString(xml,'application/xml');return{kty:'RSA',n:b64url(doc.querySelector('Modulus')?.textContent||''),e:b64url(doc.querySelector('Exponent')?.textContent||''),alg:'RSA-OAEP',ext:true,key_ops:['encrypt']}}
async function api(path,options={}){const token=options.anon?ANON:state.session?.access_token;if(!token)throw new Error('Bitte erneut anmelden.');const response=await fetch(SUPABASE+path,{method:options.method||'GET',headers:{apikey:ANON,Authorization:`Bearer ${token}`,...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})},body:options.body?JSON.stringify(options.body):undefined});const text=await response.text();let data;try{data=text?JSON.parse(text):null}catch(_){data=text}if(!response.ok)throw new Error(data?.message||data?.error_description||text||`HTTP ${response.status}`);return data}
const rpc=(name,body={})=>api(`/rest/v1/rpc/${name}`,{method:'POST',body,headers:{Prefer:'return=representation'}});
function saveSession(){localStorage.setItem('crp-mobile-session',JSON.stringify(state.session))}function logout(){localStorage.removeItem('crp-mobile-session');state.session=null;state.user=null;$('#appView').classList.add('hidden');$('#authView').classList.remove('hidden')}
async function start(session){state.session=session;saveSession();state.user=await api('/auth/v1/user');const profiles=await api(`/rest/v1/profiles?id=eq.${encodeURIComponent(state.user.id)}&select=id,display_name,contact_code`);state.profile=profiles?.[0]||{display_name:'Bote'};$('#authView').classList.add('hidden');$('#appView').classList.remove('hidden');await refresh();render()}
async function refresh(){const [rooms,clans,memberships]=await Promise.all([rpc('list_my_rooms').catch(()=>[]),api('/rest/v1/clans_250?select=*&order=name.asc').catch(()=>[]),api(`/rest/v1/clan_members_250?user_id=eq.${encodeURIComponent(state.user.id)}&select=*`).catch(()=>[])]);state.rooms=Array.isArray(rooms)?rooms:[];state.clans=Array.isArray(clans)?clans:[];state.memberships=Array.isArray(memberships)?memberships:[]}
function render(){document.querySelectorAll('[data-page]').forEach(button=>button.classList.toggle('active',button.dataset.page===state.page));if(state.page==='chats')return renderChats();if(state.page==='clans')return renderClans();if(state.page==='security')return renderSecurity();renderHome()}
function renderHome(){const unread=state.rooms.reduce((sum,room)=>sum+Number(room.unread_count||0),0);$('#page').innerHTML=`<section class="card"><p class="muted">Willkommen zurück</p><h2>${esc(state.profile?.display_name)}</h2><p>Deine E-Mail-Adresse wird anderen Nutzern nicht angezeigt.</p></section><div class="stat-grid"><div class="stat"><b>${unread}</b>ungelesen</div><div class="stat"><b>${state.memberships.length}</b>Clans</div><div class="stat"><b>${navigator.onLine?'Online':'Offline'}</b>Status</div></div><section class="card"><h2>Heute im RP</h2><div class="list">${state.rooms.slice(0,5).map(room=>`<button class="row" data-open-room="${esc(room.room_id)}"><div><b>${esc(room.name||'Chat')}</b><small>${Number(room.unread_count||0)} ungelesen</small></div><span>›</span></button>`).join('')||'<p class="muted">Noch keine Räume.</p>'}</div></section>`;bindRooms()}
function renderChats(){if(state.room)return renderRoom();$('#page').innerHTML=`<section class="card"><div class="actions"><h2 style="flex:1">Boten & Clan</h2><button data-refresh>↻</button></div><div class="list">${state.rooms.map(room=>`<button class="row" data-open-room="${esc(room.room_id)}"><div><b>${esc(room.name||'Chat')}</b><small>${esc(room.room_type||'Privat')} · ${Number(room.unread_count||0)} ungelesen</small></div><span>›</span></button>`).join('')||'<p class="muted">Noch kein Chatraum.</p>'}</div></section>`;bindRooms();$('[data-refresh]')?.addEventListener('click',async()=>{await refresh();render()})}
function bindRooms(){document.querySelectorAll('[data-open-room]').forEach(button=>button.addEventListener('click',()=>openRoom(button.dataset.openRoom)))}
async function openRoom(id){state.room=state.rooms.find(room=>String(room.room_id)===String(id))||{room_id:id,name:'Chat'};state.page='chats';$('#page').innerHTML='<section class="card">Nachrichten werden entschlüsselt …</section>';try{const rows=await api(`/rest/v1/messages?room_id=eq.${encodeURIComponent(id)}&kind=eq.chat&select=*&order=created_at.asc&limit=150`);state.messages=[];for(const item of rows||[]){let payload={body:'🔒 Kopplungsschlüssel erforderlich'};try{payload=await decrypt(item)}catch(_){}state.messages.push({...item,payload})}await rpc('mark_room_read',{target_room:id}).catch(()=>{});renderRoom()}catch(error){$('#page').innerHTML=`<section class="card"><h2>Chat nicht verfügbar</h2><p>${esc(error.message)}</p></section>`}}
function renderRoom(){const canSend=Boolean(state.key);$('#page').innerHTML=`<section class="card"><div class="actions"><button data-back>←</button><div style="flex:1"><b>${esc(state.room?.name||'Chat')}</b><small class="muted"> Ende-zu-Ende verschlüsselt</small></div><button data-reload>↻</button></div></section><div id="messages" class="chat">${state.messages.map(message=>`<div class="bubble ${String(message.sender_id)===String(state.user.id)?'mine':''}">${esc(message.payload?.body||'').replaceAll('\n','<br>')}<small>${esc(message.sender_name||'Bote')} · ${new Date(message.created_at).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}</small></div>`).join('')||'<p class="muted">Noch keine Nachrichten.</p>'}</div><form id="composer" class="composer"><textarea name="body" placeholder="${canSend?'Nachricht schreiben …':'Zuerst unter Sicher koppeln'}" ${canSend?'':'disabled'}></textarea><button class="primary" ${canSend?'':'disabled'}>➤</button></form>`;$('#messages').scrollTop=$('#messages').scrollHeight;$('[data-back]').onclick=()=>{state.room=null;renderChats()};$('[data-reload]').onclick=()=>openRoom(state.room.room_id);$('#composer').onsubmit=async event=>{event.preventDefault();const body=event.target.body.value.trim();if(!body)return;event.target.body.value='';try{await sendMessage(body);await openRoom(state.room.room_id)}catch(error){alert(error.message)}}}
async function decrypt(message){if(!state.key)throw new Error('Kein Schlüssel');const keys=typeof message.encrypted_keys==='string'?JSON.parse(message.encrypted_keys):message.encrypted_keys;const wrapped=keys?.[state.user.id];if(!wrapped)throw new Error('Nicht für dieses Konto verschlüsselt');const privateKey=await crypto.subtle.importKey('jwk',state.key.privateJwk,{name:'RSA-OAEP',hash:'SHA-1'},false,['decrypt']);const raw=await crypto.subtle.decrypt({name:'RSA-OAEP'},privateKey,unb64(wrapped));const aes=await crypto.subtle.importKey('raw',raw,{name:'AES-CBC'},false,['decrypt']);const clear=await crypto.subtle.decrypt({name:'AES-CBC',iv:unb64(message.iv)},aes,unb64(message.ciphertext));return JSON.parse(new TextDecoder().decode(clear))}
async function sendMessage(body){const recipients=await rpc('get_room_recipients',{target_room:state.room.room_id});const aes=await crypto.subtle.generateKey({name:'AES-CBC',length:256},true,['encrypt']);const raw=await crypto.subtle.exportKey('raw',aes);const iv=crypto.getRandomValues(new Uint8Array(16));const cipher=await crypto.subtle.encrypt({name:'AES-CBC',iv},aes,new TextEncoder().encode(JSON.stringify({body,sender_character:''})));const encrypted_keys={};for(const recipient of recipients||[]){const publicKey=await crypto.subtle.importKey('jwk',xmlToJwk(recipient.public_key),{name:'RSA-OAEP',hash:'SHA-1'},false,['encrypt']);encrypted_keys[recipient.id]=b64(await crypto.subtle.encrypt({name:'RSA-OAEP'},publicKey,raw))}await api('/rest/v1/messages',{method:'POST',headers:{Prefer:'return=minimal'},body:{room_id:state.room.room_id,kind:'chat',ciphertext:b64(cipher),iv:b64(iv),encrypted_keys,sender_name:state.profile?.display_name||'Bote'}})}
function renderClans(){const mine=state.clans.filter(clan=>state.memberships.some(member=>String(member.clan_id)===String(clan.id)));$('#page').innerHTML=`<section class="card"><h2>Meine Clans</h2><div class="list">${mine.map(clan=>{const member=state.memberships.find(item=>String(item.clan_id)===String(clan.id));return`<div class="row"><div><b>${esc(clan.name)}</b><small>${esc(member?.role||'Mitglied')} · ${esc(clan.server_name||'Conan RP')}</small></div><span class="badge">${esc(clan.tag||'Clan')}</span></div>`}).join('')||'<p class="muted">Noch kein Clan.</p>'}</div></section><section class="card"><h2>Clans entdecken</h2><div class="list">${state.clans.filter(clan=>!mine.includes(clan)).map(clan=>`<div class="row"><div><b>${esc(clan.name)}</b><small>${esc(clan.description||'')}</small></div><span>›</span></div>`).join('')||'<p class="muted">Keine weiteren Clans sichtbar.</p>'}</div></section>`}
function renderSecurity(){const coupled=Boolean(state.key);$('#page').innerHTML=`<section class="card"><h2>Sicherheit & Gerät</h2><p>${coupled?'✅ Dieses Gerät kann deine verschlüsselten Nachrichten lesen.':'🔒 Für Chat muss dieses Gerät einmal gekoppelt werden.'}</p><button class="primary wide" id="importKey">Kopplungsdatei importieren</button><p class="muted">Erzeuge die Datei am Desktop unter Mobile Companion → Nachrichtenschlüssel koppeln.</p></section><section class="card"><h2>Benachrichtigungen</h2><button class="wide" id="pushButton">Push-Berechtigung anfragen</button><p class="muted">Hintergrund-Push benötigt nach dem Supabase-Update noch einen VAPID-Schlüssel bzw. die mitgelieferte Edge-Function-Konfiguration.</p></section><section class="card"><button class="wide" id="logout">Abmelden</button></section>`;$('#importKey').onclick=()=>$('#keyFile').click();$('#pushButton').onclick=async()=>{const result=await Notification.requestPermission();alert(result==='granted'?'Benachrichtigungen erlaubt.':'Benachrichtigungen wurden nicht erlaubt.')};$('#logout').onclick=logout}
async function importKey(file,password){const bundle=JSON.parse(await file.text());if(bundle.format!=='conan-rp-mobile-key')throw new Error('Keine gültige Conan-RP-Kopplungsdatei.');const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);const key=await crypto.subtle.deriveKey({name:'PBKDF2',salt:unb64(bundle.salt),iterations:Number(bundle.iterations||310000),hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['decrypt']);const clear=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(bundle.iv)},key,unb64(bundle.ciphertext));state.key=JSON.parse(new TextDecoder().decode(clear));if(state.key.userId&&state.key.userId!==state.user.id)throw new Error('Diese Kopplungsdatei gehört zu einem anderen Konto.');localStorage.setItem('crp-mobile-key',JSON.stringify(state.key))}
document.querySelectorAll('.bottom-nav [data-page]').forEach(button=>button.addEventListener('click',()=>{state.page=button.dataset.page;state.room=null;render()}));$('#loginForm').addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.target);$('#authStatus').textContent='Anmeldung läuft …';api('/auth/v1/token?grant_type=password',{method:'POST',anon:true,body:{email:String(data.get('email')).trim().toLowerCase(),password:data.get('password')}}).then(start).catch(error=>$('#authStatus').textContent=error.message)});$('#keyFile').addEventListener('change',async event=>{const file=event.target.files?.[0];if(!file)return;const password=prompt('Kopplungspasswort:');if(!password)return;try{await importKey(file,password);alert('Gerät erfolgreich gekoppelt.');renderSecurity()}catch(error){alert(error.message)}});try{state.key=JSON.parse(localStorage.getItem('crp-mobile-key')||'null')}catch(_){}if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(console.warn);const stored=JSON.parse(localStorage.getItem('crp-mobile-session')||'null');if(stored?.access_token)start(stored).catch(logout);
