const CACHE='conan-rp-mobile-300-20261006-2';
const CORE=['./?v=300.1.0','index.html?v=300.1.0','styles.css?v=300.1.0','app.js?v=300.1.0','v300.js?v=300.1.0','manifest.webmanifest?v=300.1.0','icon.svg'];
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(CORE)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(Promise.all([caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE).map(key=>caches.delete(key)))),self.clients.claim()])));
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;event.respondWith(fetch(event.request).then(response=>{const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(event.request,copy));return response;}).catch(()=>caches.match(event.request)));});
self.addEventListener('push',event=>{let data={title:'Conan RP-Planer',body:'Neue Nachricht oder Clan-Aktivität',url:'./'};try{data={...data,...event.data.json()};}catch(_){}event.waitUntil(self.registration.showNotification(data.title,{body:data.body,icon:'icon.svg',badge:'icon.svg',tag:data.tag||'conan-rp',renotify:Boolean(data.renotify),data:{url:data.url||'./'}}));});
self.addEventListener('notificationclick',event=>{event.notification.close();event.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(windows=>{const existing=windows.find(client=>client.url.includes(self.registration.scope));if(existing){existing.navigate(event.notification.data?.url||'./');return existing.focus();}return clients.openWindow(event.notification.data?.url||'./');}));});
self.addEventListener('pushsubscriptionchange',event=>event.waitUntil(self.registration.pushManager.subscribe(event.oldSubscription?.options||{userVisibleOnly:true}).then(subscription=>clients.matchAll({type:'window',includeUncontrolled:true}).then(windows=>windows.forEach(client=>client.postMessage({type:'pushsubscriptionchange',subscription:subscription.toJSON()}))))));
self.addEventListener('sync',event=>{if(event.tag==='conan-rp-sync-300')event.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(windows=>windows.forEach(client=>client.postMessage({type:'sync-300'}))));});
